[package]
name = "syllog-compiler"
description = "Compilation pipeline and diagnostic rendering for Syllog"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
syllog-ir = { path = "../syllog-ir", version = "0.1.0" }
syllog-parser = { path = "../syllog-parser", version = "0.1.0" }
syllog-semantic = { path = "../syllog-semantic", version = "0.1.0" }

[lints]
workspace = true
