//! Canonical and atomically written Syllog lockfiles.

use std::io::Write;
use std::path::{Path, PathBuf};

use tempfile::NamedTempFile;
use thiserror::Error;

use crate::Resolution;

/// Lockfile serialization or persistence failure.
#[derive(Debug, Error)]
pub enum LockfileError {
    /// Canonical TOML serialization failed.
    #[error("could not serialize lockfile: {0}")]
    Serialize(#[from] toml::ser::Error),
    /// Existing lockfile syntax or schema was invalid.
    #[error("could not parse lockfile: {0}")]
    Deserialize(#[from] toml::de::Error),
    /// A filesystem operation failed.
    #[error("could not write lockfile '{}': {source}", path.display())]
    Io {
        /// Destination lockfile.
        path: PathBuf,
        /// Underlying I/O failure.
        #[source]
        source: std::io::Error,
    },
}

/// Reads a generated lockfile.
///
/// # Errors
///
/// Returns an error for I/O, syntax, or schema failures.
pub fn read_lockfile(path: &Path) -> Result<Resolution, LockfileError> {
    let text = std::fs::read_to_string(path).map_err(|source| LockfileError::Io {
        path: path.to_owned(),
        source,
    })?;
    Ok(toml::from_str(&text)?)
}

/// Serializes a resolution into canonical UTF-8 lockfile bytes.
///
/// # Errors
///
/// Returns an error if TOML serialization fails.
pub fn lockfile_bytes(resolution: &Resolution) -> Result<Vec<u8>, LockfileError> {
    let mut text = String::from("# This file is generated by Syllog. Do not edit.\n");
    text.push_str(&toml::to_string(resolution)?);
    Ok(text.into_bytes())
}

/// Atomically writes a canonical lockfile in the destination directory.
///
/// # Errors
///
/// Returns an error if serialization, temporary-file creation, durable flush,
/// or atomic persistence fails.
pub fn write_lockfile(path: &Path, resolution: &Resolution) -> Result<(), LockfileError> {
    let bytes = lockfile_bytes(resolution)?;
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    let mut temporary = NamedTempFile::new_in(parent).map_err(|source| LockfileError::Io {
        path: path.to_owned(),
        source,
    })?;
    temporary
        .write_all(&bytes)
        .and_then(|()| temporary.as_file().sync_all())
        .map_err(|source| LockfileError::Io {
            path: path.to_owned(),
            source,
        })?;
    temporary.persist(path).map_err(|error| LockfileError::Io {
        path: path.to_owned(),
        source: error.error,
    })?;
    Ok(())
}
